name: smart_parking_app
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_sliders: ^23.2.7
  flutter_credit_card: ^4.0.1
  ticket_widget: ^1.0.2
  pretty_qr_code: ^3.0.0
  getwidget: ^2.0.4
  google_fonts: 6.1.0
  animate_do: ^3.1.2
  provider: ^6.1.2
  profile: ^0.0.1
  image_picker: ^1.0.4
  table_calendar: ^3.0.9
  timer_count_down: ^2.2.0
  flutter_datetime_picker_plus: ^2.1.0
  time: "^2.1.3"
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.0
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.6.0
  http: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
